import "./globals.css";
import Navbar from "@/components/Navbar";
import NextAuthProvider from "./provider";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Notes app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <Toaster
            position="top-center"
            reverseOrder={false}
            gutter={8}
            containerClassName=""
            containerStyle={{}}
            toastOptions={{
              // Define default options
              className: "",
              duration: 5000,
              style: {
                background: "#363636",
                color: "#fff",
              },

              // Default options for specific types
              success: {
                duration: 3000,
                theme: {
                  primary: "green",
                  secondary: "black",
                },
              },
            }}
          />
          <Navbar />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
