import "./globals.css";
import Navbar from "@/components/Navbar";
import NextAuthProvider from "./provider";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Notes app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <Toaster/>
          <Navbar />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
